In [22]:
import numpy as np
import pandas as pd

arr = np.array(
    [
        [
            [1, 2, 1],
            [3, 1, 2],
        ],
        [
            [2, 1, 1],
            [1, 0, 3],
        ],
        [
            [3, 2, 1],
            [1, 0, 0],
        ],
    ]
)
print(arr, arr.shape)
print(arr.reshape(-1, 3))
df = pd.DataFrame(arr.reshape(-1, 3), columns=["red", "green", "blue"])
print(df)


[[[1 2 1]
  [3 1 2]]

 [[2 1 1]
  [1 0 3]]

 [[3 2 1]
  [1 0 0]]] (3, 2, 3)
[[1 2 1]
 [3 1 2]
 [2 1 1]
 [1 0 3]
 [3 2 1]
 [1 0 0]]
   red  green  blue
0    1      2     1
1    3      1     2
2    2      1     1
3    1      0     3
4    3      2     1
5    1      0     0


In [27]:
from ucimlrepo import fetch_ucirepo
from sklearn.preprocessing import OrdinalEncoder

ai4i_2020_predictive_maintenance_dataset = fetch_ucirepo(id=601) 
  
X = ai4i_2020_predictive_maintenance_dataset.data.features 
y = ai4i_2020_predictive_maintenance_dataset.data.targets 


In [31]:
categorical = X.select_dtypes(include=["object"]).columns
ord_enc = OrdinalEncoder()
X[categorical] = ord_enc.fit_transform(X[categorical])
print(X)
print(X.shape)

      Type  Air temperature  Process temperature  Rotational speed  Torque  \
0      2.0            298.1                308.6              1551    42.8   
1      1.0            298.2                308.7              1408    46.3   
2      1.0            298.1                308.5              1498    49.4   
3      1.0            298.2                308.6              1433    39.5   
4      1.0            298.2                308.7              1408    40.0   
...    ...              ...                  ...               ...     ...   
9995   2.0            298.8                308.4              1604    29.5   
9996   0.0            298.9                308.4              1632    31.8   
9997   2.0            299.0                308.6              1645    33.4   
9998   0.0            299.0                308.7              1408    48.5   
9999   2.0            299.0                308.7              1500    40.2   

      Tool wear  
0             0  
1             3  
2        

In [25]:
print(y[(y!=0).any(axis=1)])

      Machine failure  TWF  HDF  PWF  OSF  RNF
50                  1    0    0    1    0    0
69                  1    0    0    1    1    0
77                  1    1    0    0    0    0
160                 1    0    0    0    1    0
161                 1    0    0    0    1    0
...               ...  ...  ...  ...  ...  ...
9758                1    1    0    0    0    0
9764                1    0    0    1    0    0
9822                1    0    0    0    1    0
9830                1    0    0    0    1    0
9974                1    0    0    1    1    0

[357 rows x 6 columns]
